### ISSUE TITLE
Update Set external IP in WebRtcEndpoint.conf.ini ?

### ISSUE THREAD

**Issue by Thatoo** [manishkatyan/bbb-optimize#1]
Does this https://github.com/manishkatyan/bbb-optimize#4-set-external-ip-in-webrtcendpointconfini need update?

If I go to 
/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini

it says 
and IPv6 addresses of the media server.
;;
;; Forces all local IPv4 and/or IPv6 ICE candidates to have the given address.
;; This is really nothing more than a hack, but it's very effective to force a
;; public IP address when one is known in advance for the media server. In doing
;; so, KMS will not need a STUN or TURN server, but remote peers will still be
;; able to contact it.
;;
;; You can try using these settings if KMS is deployed on a publicly accessible
;; server, without NAT, and with a static public IP address. But if it doesn't
;; work for you, just go back to configuring a STUN or TURN server for ICE.
;;
;; Only set this parameter if you know what you're doing, and you understand
;; 100% WHY you need it. For the majority of cases, you should just prefer to
;; configure a STUN or TURN server.
;;
;; <externalIPv4> is a single IPv4 address.
;; <externalIPv6> is a single IPv6 address.
;;
;externalIPv4=198.51.100.1
;externalIPv6=2001:0db8:85a3:0000:0000:8a2e:0370:7334

;; External IP address of the media server.
;;
;; DEPRECATED: Use "externalIPv4" and/or "externalIPv6" instead.
;;
;; Forces all local IPv4 and IPv6 ICE candidates to have the given address. This
;; is really nothing more than a hack, but it's very effective to force a public
;; IP address when one is known in advance for the media server. In doing so,
;; KMS will not need a STUN or TURN server, but remote peers will still be able
;; to contact it.
;;
;; You can try using this setting if KMS is deployed on a publicly accessible
;; server, without NAT, and with a static public IP address. But if it doesn't
;; work for you, just go back to configuring a STUN or TURN server for ICE.
;;
;; Only set this parameter if you know what you're doing, and you understand
;; 100% WHY you need it. For the majority of cases, you should just prefer to

;; configure a STUN or TURN server.
;;
;; <externalAddress> is a single IPv4 or IPv6 address.
;;
;externalAddress=198.51.100.1
;externalAddress=2001:0db8:85a3:0000:0000:8a2e:0370:7334

so I guess it's note 
externalAddress=Public-IP-of-BBB-Server
that needs to be uncommented but
externalIPv4=Public-IP-of-BBB-Server

plus, I don't understand the following paragraph
STUN/TURN are needed only when the media server sits behind a NAT and needs to find out its own external IP address. However, if you set a static external IP address as mentioned above, then there is no need for the STUN/TURN auto-discovery. Hence, comment the following: using turn.higheredlab.com (IP address)

#stunServerAddress=95.217.128.91
#stunServerPort=3478

what do you exactly recommend to do?

**Comment by manishkatyan** [comment]
Updated the doc:
externalIPv4=Public-IP-of-BBB-Server

If you are installing on a BigBlueButton server behind a firewall that uses network address translation (NAT), you need to give kurento access to an external STUN server. A STUN server will help Kurento determine its external address when behind NAT. So if that's the case, you can specify the Stun server server IP:
stunServerAddress=95.217.128.91
stunServerPort=3478

However, quoting comments in /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
Forces all local IPv4 and/or IPv6 ICE candidates to have the given address. This is really nothing more than a hack, but it's very effective to force a public IP address when one is known in advance for the media server. In doing so, KMS will not need a STUN or TURN server, but remote peers will still be able to contact it.
Hence, I recommend just setting externalIPv4=Public-IP-of-BBB-Server and not using stun server. 

If setting externalIPv4 doesn't work out for you, please set stun server IP and port. 

You can use the same stun server in /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini and /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml
