### ISSUE TITLE
cat: ./env : No such file or directory

### ISSUE THREAD

**Issue by PatLemaire** [manishkatyan/bbb-optimize#11]
Hi,
Fresh install of BBB2.4 and bbb-optimize.
I create a "config-optimize" env file which is cp from your 'example-env' and modified to suit my needs…
But when i try to apply my env file with "bbb-optimize --env-file=config-optimize" this message (as in title) is displayed and no changes are applied to BBB.
I run the command from /root/bbb-custom and the file has read permission for all.

Any idea?

**Comment by arun-hel** [comment]
@PatLemaire  [7aff767](https://github.com/manishkatyan/bbb-optimize/commit/7aff7678a63691dc1c3ed3a58f3441c315b2ef74) this commit should fix the issue, please install the latest version of bigbluebutton-optimize 
```sh
#Remove  the old package
npm uninstall -g bigbluebutton-optimize

#install the latest version of bigbluebutton-optimize
npm -g i bigbluebutton-optimize
```

**Comment by PatLemaire** [comment]
No more error message with this commit. Still problems but i will open other issues.
Thanks for your work and reactivity!
