### ISSUE TITLE
is there any plan for 2.5 compatibility?

### ISSUE THREAD

**Issue by yashodhank** [manishkatyan/bbb-optimize#12]
Thank you for sharing wonderful bbb-optimize!
I would like to know if you have any plans enabling BBB version 2.5 compatibility? is it too early to ask? I am interested in testing it on my dev 2.5 rc1 instance. Thanks again!

**Comment by arun-hel** [comment]
No plans right now, but we will think about it once BBB 2.5 stable comes out. However current version of bigbluebutton-optimize should work for 2.5
