### ISSUE TITLE
Typographical Error For Learning Dashboard Cleanup Delay

### ISSUE THREAD

**Issue by DammyShittu** [manishkatyan/bbb-optimize#13]
Hi, @manishkatyan @arun-hel,

Thank you for the awesome work being done on this project. 👍 

I noticed that there is a typographical error in the [example-env](https://github.com/manishkatyan/bbb-optimize/blob/master/example-env#L60) file. `LEARNING_DASGBOARD_CLEANUP_DELAY` is currently written instead of `LEARNING_DASHBOARD_CLEANUP_DELAY`.

The error is also present in the [optimize.sh](https://github.com/manishkatyan/bbb-optimize/blob/master/bin/utils/optimize.sh#L114-L117) file.

Due to this, overriding the learning dashboard delay gives no result.

Kindly check and fix this.

Thank you. 😀

**Comment by arun-hel** [comment]
We will update it. Thanks for pointing it out.

**Comment by DammyShittu** [comment]
You are welcome, @arun-hel. Thank you for the prompt response. 👍
