### ISSUE TITLE
Download the video link of each session

### ISSUE THREAD

**Issue by cod3r0k** [manishkatyan/bbb-optimize#2]
Hi, What's your idea about converting videos to mp4 which could be downloadable?

I use https://github.com/createwebinar/bbb-download  but there is another options which I never used as https://github.com/tilmanmoser/bbb-video-download.

What is your optimized options?

If we want to have a video beside a webcams (like as Zoom or etc.), what's your idea?

**Comment by manishkatyan** [comment]
You can try our other open-sourced project to create downloadable MP4 version of recordings: https://github.com/manishkatyan/bbb-mp4

You can automate MP4 conversion and uploading to AWS S3: https://github.com/manishkatyan/bbb-mp4#automate-mp4-conversion

Plus there are a bunch of scripts, with detailed comments, to take care of manual conversion and other use cases. Check them out.

**Comment by cod3r0k** [comment]
Thanks a lot.

**Comment by cod3r0k** [comment]
It is capture Chrome browser screen? I mean that it has the same vide as playback view?

**Comment by manishkatyan** [comment]
Yes

**Comment by cod3r0k** [comment]
Can we have an output like as below?
![image](https://user-images.githubusercontent.com/36899025/99211843-8c008780-27de-11eb-9b5f-15100cbac138.png)


I'm looking for this solution. Can you help me?

**Comment by manishkatyan** [comment]
Sorry I can't. That's beyond the scope of this project.

**Comment by cod3r0k** [comment]
> Sorry I can't. That's beyond the scope of this project.

Thank you so much. If you have any guide or ideas, please share with me to collaborate . 
Thanks again

**Comment by cod3r0k** [comment]
Hi again, How can we install bbb-mp4 for BBB 2.2 ?
it is just nodjs 8 but your installation is nodejs 14.?

**Comment by manishkatyan** [comment]
Nodejs 14 would work.
