### ISSUE TITLE
Processing and published not sync

### ISSUE THREAD

**Issue by cod3r0k** [manishkatyan/bbb-optimize#3]
I have processing and also published version. Why this happend?

Is that the worker-2 works like as worker-1 ?

1b24c65c37c7105396e2be551555a8e918e87ad25-160506210765  Wed Nov 11 07:59:20 +0330 2020  X   XXXXX         12 presentation         presentation

**Comment by manishkatyan** [comment]
I am not sure I get you. Can you please elaborate a bit?

**Comment by cod3r0k** [comment]
Thanks. I mean that, when the worker 01 is processing the video, I think another ones also process the other ones. When one of them wants to publish one video, the other start to process that video (the video which worker 01 is processed it).

in `1b24c65c37c7105396e2be551555a8e918e87ad25-160506210765 Wed Nov 11 07:59:20 +0330 2020 X XXXXX 12 presentation presentation` As you can see, we have presentation in two column. (It is the output record of `bbb-record --list`)

It showed that the files is also in both processing dir and published dir.

But when I never launch two worker in another server, It is just have one `presentation` in column of published videos.

**Comment by manishkatyan** [comment]
process 1 will only pick records ending with [0-4]$ and process 2 will only pick records ending with [5-9]$. So it should not happen that both the process are picking the same record. 

Can you check and confirm if you are getting both the records published after a while?

**Comment by cod3r0k** [comment]
> process 1 will only pick records ending with [0-4]$ and process 2 will only pick records ending with [5-9]$. So it should not happen that both the process are picking the same record.
> 
> Can you check and confirm if you are getting both the records published after a while?

I don't remember that ids but I think you are correct! Thanks a lot.

Can we setup another worker? for example [1-3] [3-7] [7-0] ؟

**Comment by manishkatyan** [comment]
>>Can we setup another worker? for example [1-3] [3-7] [7-0] ؟
I have not tried. Feel free to experiment. Small correction in the range: [1-3][4-7][8-0]

Also closing this as original issue is resolved.
