### ISSUE TITLE
what is right path of external.xml?

### ISSUE THREAD

**Issue by mabras** [manishkatyan/bbb-optimize#4]
The README reference this path:
`/opt/freeswitch/conf/sip_profiles/external.xml`

The BBB reference this in their docs and `bbb-conf --check`
`/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml`

I just want to sure if both are the same. If they are, I suggest using the second to avoid any confusion

**Comment by manishkatyan** [comment]
Both /opt/freeswitch/conf/sip_profiles/external.xml and /opt/freeswitch/etc/freeswitch/sip_profiles/external.xml are same. 

For consistency, updated README and apply-config-sample.sh to use BBB reference doc path. 

Thanks for your suggestion!
