### ISSUE TITLE
5349 not 5439

### ISSUE THREAD

**Issue by Thatoo** [manishkatyan/bbb-optimize#5]
Hello,

You wrote
Ensure that ufw firewall on your Turn server allows the following ports: 80, 443, 3478, 5439, and 49152:65535/udp
instead of
Ensure that ufw firewall on your Turn server allows the following ports: 80, 443, 3478, 5349, and 49152:65535/udp

Best regards,

**Comment by manishkatyan** [comment]
Thanks for pointing out the typo. We recently updated Turn installation which is simpler (no alt ports) and works well. So no more need for opening 80 and 5439 ports on UFW.
