### ISSUE TITLE
Discuss: Error 1007 when already setup turn server

### ISSUE THREAD

**Issue by phamquocthinh** [manishkatyan/bbb-optimize#6]
Hi,
I have an issue with bbb when connected to audio
I've setup a turn server and use with bbb, it only work when I set

media.peerconnection.ice.relay_only | true

on firefox, other always throw 1007

Could you please help?
Thank you in advance

**Comment by manishkatyan** [comment]
You should verify your Turn server installation - https://github.com/manishkatyan/bbb-optimize#3-install-turn-coturn-server
It would work correctly.
