### ISSUE TITLE
Working solution for higher webcam quality

### ISSUE THREAD

**Issue by misisol** [manishkatyan/bbb-optimize#7]
Hi,
Thanks for your useful information you have gathered through your git.
I wanted to ask if you have found a working solution to get a better webcam quality ( like HD ) from bigbluebutton.

regards.

**Comment by manishkatyan** [comment]
Try this:

vi /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
Go to cameraProfiles:
Make default as true for the resolution that you want to have.
